# Generated by Django 3.1.4 on 2021-01-06 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainForm',
            new_name='Application',
        ),
    ]
