# Generated by Django 3.1.4 on 2021-01-06 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MainForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('service', models.CharField(max_length=64)),
                ('comment', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TypeRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('countrooms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.countrooms')),
            ],
        ),
        migrations.CreateModel(
            name='TypeClean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.place')),
            ],
        ),
        migrations.AddField(
            model_name='countrooms',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.place'),
        ),
        migrations.CreateModel(
            name='Clean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('countrooms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.countrooms')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.place')),
                ('typeclean', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.typeclean')),
                ('typyrooms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.typerooms')),
            ],
        ),
    ]
