# Generated by Django 3.1.4 on 2021-01-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210107_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clean',
            old_name='typyrooms',
            new_name='typerooms',
        ),
    ]
