# Generated by Django 3.1.4 on 2021-01-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210107_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
