# Generated by Django 3.1.4 on 2021-01-07 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20210107_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clean',
            name='count_rooms',
        ),
    ]
