# Generated by Django 3.1.4 on 2021-01-07 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_remove_clean_count_rooms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountRooms',
        ),
    ]
