# Generated by Django 3.1.4 on 2021-01-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_auto_20210109_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrooms',
            old_name='count',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='clean',
            name='count_rooms',
        ),
    ]
