# Generated by Django 3.1.4 on 2021-01-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210107_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrooms',
            name='name',
        ),
        migrations.AddField(
            model_name='countrooms',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
