# Generated by Django 3.1.4 on 2021-01-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_clean_count_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clean',
            name='count_rooms',
            field=models.CharField(max_length=64),
        ),
    ]
