# Generated by Django 3.1.4 on 2021-01-07 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_countrooms_clean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrooms',
            name='clean',
        ),
        migrations.AlterField(
            model_name='clean',
            name='count_rooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.countrooms'),
        ),
    ]
