# Generated by Django 3.1.4 on 2021-01-10 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_remove_clean_count_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeclean',
            name='place',
        ),
        migrations.DeleteModel(
            name='TypeRooms',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='TypeClean',
        ),
    ]
