# Generated by Django 3.1.4 on 2021-01-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210107_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clean',
        ),
        migrations.RemoveField(
            model_name='typeclean',
            name='place',
        ),
        migrations.RemoveField(
            model_name='typerooms',
            name='countrooms',
        ),
        migrations.DeleteModel(
            name='CountRooms',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='TypeClean',
        ),
        migrations.DeleteModel(
            name='TypeRooms',
        ),
    ]
