# Generated by Django 3.1.4 on 2021-01-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210107_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clean',
            old_name='countrooms',
            new_name='count_rooms',
        ),
        migrations.RenameField(
            model_name='clean',
            old_name='typeclean',
            new_name='type_clean',
        ),
        migrations.RenameField(
            model_name='clean',
            old_name='typerooms',
            new_name='type_rooms',
        ),
    ]
