# Generated by Django 3.1.4 on 2021-01-07 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_clean_count_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typerooms',
            name='countrooms',
        ),
        migrations.DeleteModel(
            name='CountRooms',
        ),
    ]
