# Generated by Django 3.1.4 on 2021-01-07 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20210107_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='clean',
            name='count_rooms',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='book.countrooms'),
            preserve_default=False,
        ),
    ]
