# Generated by Django 3.1.4 on 2021-01-07 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20210107_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clean',
            name='count_rooms',
        ),
    ]
