# Generated by Django 3.1.4 on 2021-01-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_auto_20210109_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clean',
            name='count_rooms',
        ),
        migrations.AddField(
            model_name='clean',
            name='count_rooms',
            field=models.ManyToManyField(to='book.CountRooms'),
        ),
        migrations.AlterField(
            model_name='countrooms',
            name='count',
            field=models.CharField(max_length=64),
        ),
    ]
