# Generated by Django 3.1.4 on 2021-01-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_auto_20210109_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountRooms',
        ),
        migrations.AddField(
            model_name='clean',
            name='count_rooms',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
