# Generated by Django 3.1.4 on 2021-01-07 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20210107_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clean',
            name='count_rooms',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='book.countrooms'),
        ),
    ]
