# Generated by Django 3.1.4 on 2021-01-07 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20210107_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clean',
            name='count_rooms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='book.countrooms'),
        ),
    ]
