# Generated by Django 3.1.4 on 2021-01-09 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_auto_20210109_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clean',
            name='count_rooms',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='countrooms',
            name='count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.clean'),
        ),
    ]
