# Generated by Django 3.1.4 on 2021-01-07 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210106_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='name',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='typeclean',
            old_name='name',
            new_name='name2',
        ),
    ]
